In [5]:
import os
import glob
import pandas as pd
import numpy as np
from datetime import datetime
from nemosis import static_table
from datetime import timedelta

raw_data_cache = '/Volumes/T7/NEMO-misc'

In [2]:
# # Join DUIDs with firm names and further info
# generator_info_df = static_table(table_name='Generators and Scheduled Loads', 
#                               raw_data_location=raw_data_cache,
#                               update_static_file=False)
# generator_info_df

In [3]:
# # Join generator info with volume bid table on DUIDs
# def match_generators_with_info(input_dir, output_dir, raw_data_cache):
#     """
#     Match generator DUIDs in filtered bid data with generator information
#     to add details about stations, firms, and states.
    
#     Parameters:
#     -----------
#     input_dir : str
#         Directory containing filtered parquet files (bid-volume-filtered-3)
#     output_dir : str
#         Directory where enriched files will be saved
#     raw_data_cache : str
#         Path to the raw NEMOSIS data cache for fetching generator information
#     """
#     print(f"Starting generator information matching process...")
    
#     # Get list of all parquet files in the input directory
#     file_list = glob.glob(os.path.join(input_dir, "*.parquet"))
    
#     # Sort the file list to ensure consistent processing order
#     file_list.sort()
    
#     print(f"Found {len(file_list)} parquet files to process")
    
#     # Process each file
#     total_files = len(file_list)
#     for idx, file_path in enumerate(file_list, start=1):
#         file_name = os.path.basename(file_path)
#         print(f"Processing file {idx}/{total_files}: {file_name}")
        
#         try:
#             # Read the parquet file
#             df = pd.read_parquet(file_path)
            
#             # Check that DUID column exists
#             if 'DUID' not in df.columns:
#                 print(f"  - Warning: DUID column not found in {file_name}, skipping file")
#                 continue
            
#             # Count unique DUIDs before merging
#             original_duids = df['DUID'].unique()
#             print(f"  - File contains {len(original_duids)} unique DUIDs")
            
#             # Merge with generator information
#             enriched_df = pd.merge(
#                 df, 
#                 generator_info_df, 
#                 on='DUID', 
#                 how='left'
#             )
            
#             # Check if there are any DUIDs that didn't match
#             matched_duids = enriched_df.dropna(subset=['Station Name']).copy()
#             unmatched_count = len(df) - len(matched_duids)
            
#             if unmatched_count > 0:
#                 print(f"  - Warning: {unmatched_count} rows ({unmatched_count/len(df)*100:.1f}%) have DUIDs not found in generator info")
#                 unmatched_duids = enriched_df[enriched_df['Station Name'].isna()]['DUID'].unique()
#                 print(f"  - Sample of unmatched DUIDs: {list(unmatched_duids)[:5]}")
            
#             # Construct output file path
#             output_file_path = os.path.join(output_dir, file_name)
            
#             # Save the enriched DataFrame to a new parquet file
#             enriched_df.to_parquet(output_file_path, index=False)
#             print(f"  - Saved enriched data to {output_file_path}")
            
#         except Exception as e:
#             print(f"  - Error processing {file_name}: {str(e)}")
    
#     print("\nProcessing complete!")
#     print(f"Enriched data saved to {output_dir}")
    

# if __name__ == "__main__":
#     # Directories
#     input_directory = "/Volumes/T7/bid-volume-filtered-3"  # 18:05:00 filtered data
#     output_directory = "/Volumes/T7/bid-volume-enriched"   # Where to save enriched data
#     raw_data_cache = "/Volumes/T7/NEMO-misc"               # Path to NEMOSIS cache
    
#     # Match generator information with DUID
#     match_generators_with_info(
#         input_dir=input_directory,
#         output_dir=output_directory,
#         raw_data_cache=raw_data_cache
#     )

In [2]:
import glob
import os
import dask.dataframe as dd

directory = "/Volumes/T7/bid-volume-enriched_sa1-A4"
all_files = glob.glob(os.path.join(directory, "*.parquet"))

# Filter out files that start with '._'
parquet_files = [f for f in all_files if not os.path.basename(f).startswith("._")]

# Now read only the valid parquet files
ddf = dd.read_parquet(parquet_files)
pdf = ddf.compute()

In [3]:
pdf.head()

,SETTLEMENTDATE,DUID,BIDTYPE,OFFERDATE,MAXAVAIL,ENABLEMENTMIN,ENABLEMENTMAX,LOWBREAKPOINT,HIGHBREAKPOINT,BANDAVAIL1,...,Station Name,Region,Dispatch Type,Category,Classification,Fuel Source - Primary,Fuel Source - Descriptor,Technology Type - Primary,Technology Type - Descriptor,Aggregation
591,2009/07/01 00:00:00,PPCCGT,LOWER60SEC,2009/07/01 02:17:42,0,333,480,333,480,15,...,Pelican Point Power Station,SA1,Generating Unit,Market,Scheduled,Fossil,Natural Gas,Combustion,Combined Cycle Gas Turbine (CCGT),Y
592,2009/07/01 00:00:00,PPCCGT,LOWER6SEC,2009/07/01 02:17:42,30,333,480,363,480,15,...,Pelican Point Power Station,SA1,Generating Unit,Market,Scheduled,Fossil,Natural Gas,Combustion,Combined Cycle Gas Turbine (CCGT),Y
593,2009/07/01 00:00:00,PPCCGT,LOWERREG,2009/07/01 02:17:42,30,333,480,363,480,0,...,Pelican Point Power Station,SA1,Generating Unit,Market,Scheduled,Fossil,Natural Gas,Combustion,Combined Cycle Gas Turbine (CCGT),Y
594,2009/07/01 00:00:00,PPCCGT,RAISE60SEC,2009/07/01 02:17:42,0,333,480,333,480,15,...,Pelican Point Power Station,SA1,Generating Unit,Market,Scheduled,Fossil,Natural Gas,Combustion,Combined Cycle Gas Turbine (CCGT),Y
595,2009/07/01 00:00:00,PPCCGT,RAISE6SEC,2009/07/01 02:17:42,30,333,480,333,450,15,...,Pelican Point Power Station,SA1,Generating Unit,Market,Scheduled,Fossil,Natural Gas,Combustion,Combined Cycle Gas Turbine (CCGT),Y

In [1]:
import dask.dataframe as dd
import pandas as pd
import glob
import os

# Get list of actual parquet files (excluding hidden files)
parquet_files = [f for f in glob.glob("/Volumes/T7/bid-volume-enriched_sa1-A4/*.parquet") 
                if not os.path.basename(f).startswith("._")]

# Read the specific files
ddf = dd.read_parquet(parquet_files)

# Continue with your data processing
pdf = ddf.compute()
pdf.head()

,SETTLEMENTDATE,DUID,BIDTYPE,OFFERDATE,MAXAVAIL,ENABLEMENTMIN,ENABLEMENTMAX,LOWBREAKPOINT,HIGHBREAKPOINT,BANDAVAIL1,...,Station Name,Region,Dispatch Type,Category,Classification,Fuel Source - Primary,Fuel Source - Descriptor,Technology Type - Primary,Technology Type - Descriptor,Aggregation
591,2009/07/01 00:00:00,PPCCGT,LOWER60SEC,2009/07/01 02:17:42,0,333,480,333,480,15,...,Pelican Point Power Station,SA1,Generating Unit,Market,Scheduled,Fossil,Natural Gas,Combustion,Combined Cycle Gas Turbine (CCGT),Y
592,2009/07/01 00:00:00,PPCCGT,LOWER6SEC,2009/07/01 02:17:42,30,333,480,363,480,15,...,Pelican Point Power Station,SA1,Generating Unit,Market,Scheduled,Fossil,Natural Gas,Combustion,Combined Cycle Gas Turbine (CCGT),Y
593,2009/07/01 00:00:00,PPCCGT,LOWERREG,2009/07/01 02:17:42,30,333,480,363,480,0,...,Pelican Point Power Station,SA1,Generating Unit,Market,Scheduled,Fossil,Natural Gas,Combustion,Combined Cycle Gas Turbine (CCGT),Y
594,2009/07/01 00:00:00,PPCCGT,RAISE60SEC,2009/07/01 02:17:42,0,333,480,333,480,15,...,Pelican Point Power Station,SA1,Generating Unit,Market,Scheduled,Fossil,Natural Gas,Combustion,Combined Cycle Gas Turbine (CCGT),Y
595,2009/07/01 00:00:00,PPCCGT,RAISE6SEC,2009/07/01 02:17:42,30,333,480,333,450,15,...,Pelican Point Power Station,SA1,Generating Unit,Market,Scheduled,Fossil,Natural Gas,Combustion,Combined Cycle Gas Turbine (CCGT),Y

In [5]:
import os
import glob
import pandas as pd
import re

# List of band columns we want to melt
band_cols = [f"BANDAVAIL{i}" for i in range(1, 11)]

def melt_one_file(input_path, output_dir):
    """
    Reads one Parquet file into memory, melts the BANDAVAIL columns,
    and saves the melted data to a new Parquet file in output_dir.
    """
    try:
        # 1) Read the single Parquet file into a pandas DataFrame
        df = pd.read_parquet(input_path)

        # 2) Identify all other columns as id_vars
        id_vars_cols = [col for col in df.columns if col not in band_cols]

        # 3) Melt the DataFrame
        df_long = pd.melt(
            df,
            id_vars=id_vars_cols,
            value_vars=band_cols,
            var_name="BIDBAND",
            value_name="BIDVOLUME"
        )

        # 4) Convert "BIDBAND" from e.g. "BANDAVAIL1" -> integer 1
        df_long["BIDBAND"] = df_long["BIDBAND"].str.extract(r"BANDAVAIL(\d+)").astype(int)

        # 5) Construct the output file path - FIXED
        base_name = os.path.basename(input_path)
        
        # Get the file number from the original filename
        match = re.search(r'part\.(\d+)\.parquet', base_name)
        if match:
            file_num = match.group(1)
            # Create new filename with consistent formatting
            melted_name = f"part.{file_num}_melted.parquet"
        else:
            # If no match found, use a safe fallback
            melted_name = base_name.replace(".parquet", "_melted.parquet")
            
        output_path = os.path.join(output_dir, melted_name)

        # 6) Save melted data to a new Parquet file
        df_long.to_parquet(output_path, index=False)
        print(f"Melted file saved to {output_path}")
        return output_path
    except Exception as e:
        print(f"Error processing {input_path}: {str(e)}")
        return None


def main():
    input_dir = "/Volumes/T7/bid-volume-enriched_sa1-A4"  # Where your original Parquet files live
    output_dir = "/Volumes/T7/bid-volume-melted-files"    # Where to save melted files
    os.makedirs(output_dir, exist_ok=True)

    # Gather Parquet files
    parquet_files = glob.glob(os.path.join(input_dir, "*.parquet"))
    
    # Extract numerical part for proper sorting
    def get_file_number(filepath):
        match = re.search(r'part\.(\d+)\.parquet', os.path.basename(filepath))
        if match:
            return int(match.group(1))
        return 0  # Default for files that don't match the pattern
    
    # Sort files numerically by their part number
    parquet_files = sorted(parquet_files, key=get_file_number)
    
    # Exclude hidden macOS files
    parquet_files = [f for f in parquet_files if not os.path.basename(f).startswith("._")]

    print(f"Found {len(parquet_files)} Parquet files in {input_dir}.")

    # Process each file individually and collect results
    processed_files = []
    for i, file_path in enumerate(parquet_files):
        output_path = melt_one_file(file_path, output_dir)
        if output_path:
            processed_files.append(output_path)
        
        # Print progress every 10 files
        if (i + 1) % 10 == 0:
            print(f"Processed {i + 1}/{len(parquet_files)} files")

    print(f"Successfully processed {len(processed_files)} out of {len(parquet_files)} files.")
    
    # Verify output files
    print("\nVerifying output files:")
    for i, file_path in enumerate(processed_files[:10]):  # Print first 10 for verification
        print(f"  {i+1}. {os.path.basename(file_path)}")
    
    print("All files melted and saved!")


if __name__ == "__main__":
    main()

Found 1580 Parquet files in /Volumes/T7/bid-volume-enriched_sa1-A4.
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.0_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.1_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.2_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.3_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.4_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.5_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.6_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.7_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.8_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.9_melted.parquet
Processed 10/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.10_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.11_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.12_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.13_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.14_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.15_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.16_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.17_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.18_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.19_melted.parquet
Processed 20/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.20_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.21_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.22_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.23_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.24_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.25_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.26_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.27_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.28_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.29_melted.parquet
Processed 30/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.30_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.31_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.32_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.33_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.34_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.35_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.36_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.37_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.38_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.39_melted.parquet
Processed 40/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.40_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.41_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.42_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.43_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.44_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.45_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.46_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.47_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.48_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.49_melted.parquet
Processed 50/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.50_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.51_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.52_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.53_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.54_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.55_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.56_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.57_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.58_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.59_melted.parquet
Processed 60/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.60_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.61_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.62_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.63_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.64_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.65_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.66_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.67_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.68_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.69_melted.parquet
Processed 70/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.70_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.71_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.72_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.73_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.74_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.75_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.76_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.77_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.78_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.79_melted.parquet
Processed 80/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.80_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.81_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.82_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.83_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.84_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.85_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.86_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.87_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.88_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.89_melted.parquet
Processed 90/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.90_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.91_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.92_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.93_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.94_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.95_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.96_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.97_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.98_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.99_melted.parquet
Processed 100/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.100_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.101_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.102_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.103_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.104_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.105_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.106_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.107_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.108_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.109_melted.parquet
Processed 110/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.110_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.111_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.112_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.113_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.114_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.115_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.116_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.117_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.118_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.119_melted.parquet
Processed 120/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.120_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.121_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.122_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.123_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.124_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.125_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.126_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.127_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.128_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.129_melted.parquet
Processed 130/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.130_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.131_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.132_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.133_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.134_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.135_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.136_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.137_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.138_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.139_melted.parquet
Processed 140/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.140_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.141_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.142_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.143_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.144_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.145_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.146_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.147_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.148_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.149_melted.parquet
Processed 150/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.150_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.151_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.152_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.153_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.154_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.155_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.156_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.157_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.158_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.159_melted.parquet
Processed 160/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.160_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.161_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.162_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.163_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.164_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.165_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.166_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.167_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.168_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.169_melted.parquet
Processed 170/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.170_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.171_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.172_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.173_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.174_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.175_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.176_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.177_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.178_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.179_melted.parquet
Processed 180/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.180_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.181_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.182_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.183_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.184_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.185_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.186_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.187_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.188_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.189_melted.parquet
Processed 190/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.190_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.191_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.192_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.193_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.194_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.195_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.196_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.197_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.198_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.199_melted.parquet
Processed 200/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.200_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.201_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.202_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.203_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.204_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.205_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.206_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.207_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.208_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.209_melted.parquet
Processed 210/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.210_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.211_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.212_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.213_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.214_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.215_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.216_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.217_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.218_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.219_melted.parquet
Processed 220/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.220_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.221_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.222_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.223_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.224_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.225_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.226_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.227_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.228_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.229_melted.parquet
Processed 230/1580 files
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.230_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.231_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.232_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.233_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.234_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.235_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.236_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.237_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.238_melted.parquet
Melted file saved to /Volumes/T7/bid-volume-melted-files/part.239_melted.parquet
Processed 240/1580 files

In [ ]:
import os
import glob
import pandas as pd
from datetime import timedelta

# Define which columns to melt
price_band_cols = [f"PRICEBAND{i}" for i in range(1, 11)]

def melt_one_price_file(input_path, output_dir):
    """
    Reads one Parquet file (price bids) into memory,
    melts the PRICEBAND columns into a single column,
    and saves the melted data to a new Parquet file in output_dir.
    """
    # 1) Read the single Parquet file into a pandas DataFrame
    df = pd.read_parquet(input_path)

    # 2) Identify all other columns as id_vars
    id_vars_cols = [col for col in df.columns if col not in price_band_cols]

    # 3) Melt the DataFrame
    df_long = pd.melt(
        df,
        id_vars=id_vars_cols,
        value_vars=price_band_cols,
        var_name="BIDBAND",
        value_name="BIDPRICE"
    )

    # 4) Convert "BIDBAND" from e.g. "PRICEBAND1" -> integer 1
    df_long["BIDBAND"] = df_long["BIDBAND"].str.extract(r"(\d+)").astype(int)

    # 5) (Optional) Convert other columns to consistent dtypes
    #    Adjust column names if they differ in your data
    if "BIDTYPE" in df_long.columns:
        df_long["BIDTYPE"] = df_long["BIDTYPE"].astype(str)
    if "DUID" in df_long.columns:
        df_long["DUID"] = df_long["DUID"].astype(str)
    if "SETTLEMENTDATE" in df_long.columns:
        df_long["SETTLEMENTDATE"] = pd.to_datetime(df_long["SETTLEMENTDATE"])
        # Add 4 hours, 5 minutes offset for APPLICABLEFROM
        df_long["APPLICABLEFROM"] = df_long["SETTLEMENTDATE"] + timedelta(hours=4, minutes=5)
        df_long["APPLICABLEFROM"] = pd.to_datetime(df_long["APPLICABLEFROM"])

    # 6) Construct the output file path
    base_name = os.path.basename(input_path)
    melted_name = base_name.replace(".parquet", "_melted.parquet")
    output_path = os.path.join(output_dir, melted_name)

    # 7) Save melted data to a new Parquet file
    df_long.to_parquet(output_path, index=False)
    print(f"Melted file saved to {output_path}")

def main():
    input_dir = "/Volumes/T7/bid-price-data-excluding-energy-B2"  # Where your price Parquet files live
    output_dir = "/Volumes/T7/bid-price-melted-files"  # Where to save melted files
    os.makedirs(output_dir, exist_ok=True)

    # Gather Parquet files
    parquet_files = sorted(glob.glob(os.path.join(input_dir, "*.parquet")))
    # Exclude hidden macOS files
    parquet_files = [f for f in parquet_files if not os.path.basename(f).startswith("._")]

    print(f"Found {len(parquet_files)} Parquet files in {input_dir}.")

    # Process each file individually
    for file_path in parquet_files:
        melt_one_price_file(file_path, output_dir)

    print("All price files melted and saved!")

if __name__ == "__main__":
    main()

Found 1452 Parquet files in /Volumes/T7/bid-price-data-excluding-energy-B2.
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20090701_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20090801_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20090901_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20091001_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20091101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20091201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20100101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20100201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20100301_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20100401_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20100501_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20100601_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20100701_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20100801_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20100901_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20101001_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20101101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20101201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20110101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20110201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20110301_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20110401_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20110501_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20110601_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20110701_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20110801_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20110901_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20111001_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20111101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20111201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20120101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20120201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20120301_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20120401_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20120501_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20120601_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20120701_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20120801_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20120901_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20121001_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20121101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20121201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20130101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20130201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20130301_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20130401_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20130501_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20130601_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20130701_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20130801_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20130901_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20131001_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20131101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20131201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20140101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20140201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20140301_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20140401_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20140501_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20140601_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20140701_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20140801_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20140901_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20141001_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20141101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20141201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20150101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20150201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20150301_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20150401_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20150501_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20150601_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20150701_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20150801_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20150901_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20151001_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20151101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20151201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20160101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20160201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20160301_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20160401_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20160501_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20160601_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20160701_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20160801_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20160901_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20161001_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20161101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20161201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20170101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20170201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20170301_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20170401_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20170501_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20170601_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20170701_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20170801_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20170901_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20171001_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20171101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20171201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20180101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20180201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20180301_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20180401_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20180501_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20180601_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20180701_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20180801_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20180901_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20181001_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20181101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20181201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20190101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20190201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20190301_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20190401_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20190501_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20190601_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20190701_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20190801_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20190901_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20191001_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20191101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20191201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20200101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20200201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20200301_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20200401_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20200501_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20200601_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20200701_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20200801_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20200901_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20201001_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20201101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20201201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210101_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210201_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210401_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210402_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210403_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210404_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210405_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210406_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210407_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210408_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210409_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210410_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210411_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210412_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210413_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210414_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210415_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210416_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210417_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210418_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210419_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210420_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210421_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210422_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210423_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210424_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210425_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210426_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210427_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210428_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210429_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210430_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210501_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210502_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210503_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210504_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210505_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210506_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210507_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210508_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210509_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210510_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210511_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210512_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210513_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210514_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210515_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210516_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210517_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210518_melted.parquet
Melted file saved to /Volumes/T7/bid-price-melted-files/PUBLIC_DVD_BIDDAYOFFER_D_20210519_melted.parquet

In [10]:
import glob
import os
import dask.dataframe as dd
import pandas as pd
import tempfile

def load_valid_parquet_files(folder_pattern):
    """
    Load all valid parquet files matching the given pattern into a Dask DataFrame.
    Excludes hidden files (like macOS ._* files).
    
    Args:
        folder_pattern: Glob pattern to match parquet files
        
    Returns:
        Dask DataFrame containing the data from all valid parquet files
    """
    # Get all files matching the pattern
    all_files = glob.glob(folder_pattern)
    
    # Filter out hidden files (like macOS ._ files)
    valid_files = [f for f in all_files if not os.path.basename(f).startswith('._')]
    
    # Sort files to ensure consistent reading order
    valid_files = sorted(valid_files)
    
    print(f"Found {len(valid_files)} valid parquet files from pattern: {folder_pattern}")
    
    if not valid_files:
        raise ValueError(f"No valid parquet files found for pattern: {folder_pattern}")
    
    # Load files into a Dask DataFrame
    return dd.read_parquet(valid_files, engine='pyarrow')

def process_data_in_chunks(volume_ddf, price_ddf, output_dir, chunk_size=1000000):
    """
    Process the data chunk by chunk to avoid memory issues.
    
    This method:
    1. Writes each dataframe to temporary CSV files
    2. Loads chunks of data from those files
    3. Merges the chunks
    4. Writes the results to parquet files
    """
    os.makedirs(output_dir, exist_ok=True)
    
    # Write volume dataframe to temporary CSV files
    print("Writing volume data to temporary CSV files...")
    with tempfile.TemporaryDirectory() as volume_temp_dir:
        volume_temp_path = os.path.join(volume_temp_dir, "volume_data_*.csv")
        volume_ddf.to_csv(volume_temp_path, index=False)
        
        # Get the actual CSV files created
        volume_csv_files = sorted(glob.glob(os.path.join(volume_temp_dir, "*.csv")))
        print(f"Volume data written to {len(volume_csv_files)} temporary CSV files")
        
        # Write price dataframe to temporary CSV files
        print("Writing price data to temporary CSV files...")
        with tempfile.TemporaryDirectory() as price_temp_dir:
            price_temp_path = os.path.join(price_temp_dir, "price_data_*.csv")
            price_ddf.to_csv(price_temp_path, index=False)
            
            # Get the actual CSV files created
            price_csv_files = sorted(glob.glob(os.path.join(price_temp_dir, "*.csv")))
            print(f"Price data written to {len(price_csv_files)} temporary CSV files")
            
            # Process each volume CSV file one by one
            for i, volume_file in enumerate(volume_csv_files):
                print(f"Processing volume file {i+1}/{len(volume_csv_files)}: {volume_file}")
                
                # Read the volume data as pandas DataFrame
                volume_df = pd.read_csv(volume_file)
                volume_df["SETTLEMENTDATE"] = pd.to_datetime(volume_df["SETTLEMENTDATE"], errors="coerce")
                
                # Process each price CSV file against this volume file
                for j, price_file in enumerate(price_csv_files):
                    print(f"  Merging with price file {j+1}/{len(price_csv_files)}: {price_file}")
                    
                    # Read the price data as pandas DataFrame
                    price_df = pd.read_csv(price_file)
                    price_df["SETTLEMENTDATE"] = pd.to_datetime(price_df["SETTLEMENTDATE"], errors="coerce")
                    
                    # Merge the DataFrames
                    merged_df = volume_df.merge(
                        price_df,
                        on=["SETTLEMENTDATE", "DUID", "BIDTYPE", "BIDBAND"],
                        how="inner",
                        suffixes=('_volume', '_price')
                    )
                    
                    # If we have merged data, write it to a parquet file
                    if not merged_df.empty:
                        output_file = os.path.join(output_dir, f"merged_v{i}_p{j}.parquet")
                        merged_df.to_parquet(output_file, engine='pyarrow', index=False)
                        print(f"    Wrote {len(merged_df)} rows to {output_file}")
                    else:
                        print(f"    No matching data between these files")

def main():
    # Set up paths for input files
    volume_pattern = "/Volumes/T7/bid-volume-melted-files-A4/*.parquet"
    price_pattern = "/Volumes/T7/bid-price-melted-files-B3/*.parquet"
    
    print("Loading volume data...")
    volume_ddf = load_valid_parquet_files(volume_pattern)
    print(f"Volume data columns: {list(volume_ddf.columns)}")
    print(f"Volume data partitions: {volume_ddf.npartitions}")
    
    print("Loading price data...")
    price_ddf = load_valid_parquet_files(price_pattern)
    print(f"Price data columns: {list(price_ddf.columns)}")
    print(f"Price data partitions: {price_ddf.npartitions}")
    
    # Convert SETTLEMENTDATE to datetime if needed (just defining the operation, not computing)
    print("Defining datetime conversion for SETTLEMENTDATE...")
    volume_ddf = volume_ddf.assign(
        SETTLEMENTDATE=dd.to_datetime(volume_ddf["SETTLEMENTDATE"], errors="coerce")
    )
    price_ddf = price_ddf.assign(
        SETTLEMENTDATE=dd.to_datetime(price_ddf["SETTLEMENTDATE"], errors="coerce")
    )
    
    # Create output directory if it doesn't exist
    output_dir = "/Volumes/T7/bid-merged-fcas"
    print(f"Will save merged data to {output_dir}...")
    
    # Process data in chunks
    process_data_in_chunks(volume_ddf, price_ddf, output_dir)
    
    # Report completion
    print("All done!")
    print(f"Output saved to: {output_dir}")

if __name__ == "__main__":
    main()

Loading volume data...
Found 1580 valid parquet files from pattern: /Volumes/T7/bid-volume-melted-files-A4/*.parquet
Volume data columns: ['SETTLEMENTDATE', 'DUID', 'BIDTYPE', 'OFFERDATE', 'MAXAVAIL', 'ENABLEMENTMIN', 'ENABLEMENTMAX', 'LOWBREAKPOINT', 'HIGHBREAKPOINT', 'INTERVAL_DATETIME', 'Participant', 'Station Name', 'Region', 'Dispatch Type', 'Category', 'Classification', 'Fuel Source - Primary', 'Fuel Source - Descriptor', 'Technology Type - Primary', 'Technology Type - Descriptor', 'Aggregation', 'BIDBAND', 'BIDVOLUME']
Volume data partitions: 1580
Loading price data...
Found 1452 valid parquet files from pattern: /Volumes/T7/bid-price-melted-files-B3/*.parquet
Price data columns: ['SETTLEMENTDATE', 'DUID', 'BIDTYPE', 'OFFERDATE', 'VERSIONNO', 'MINIMUMLOAD', 'T1', 'T2', 'T3', 'T4', 'BIDBAND', 'BIDPRICE', 'APPLICABLEFROM']
Price data partitions: 1452
Defining datetime conversion for SETTLEMENTDATE...
Will save merged data to /Volumes/T7/bid-merged-fcas...
Writing volume data to temporary CSV files...

KeyboardInterrupt:

In [4]:
output_file = "/Volumes/T7/melted-bids/bid-merged.parquet"
merged_pdf.to_parquet(output_file, index=False)

print(f"Saved merged DataFrame to {output_file}")

Saved merged DataFrame to /Volumes/T7/melted-bids/bid-merged.parquet

In [ ]:
# import dask.dataframe as dd

# volume_ddf = dd.read_parquet('/Volumes/T7/melted-bids/bid-volume-melted.parquet')
# price_ddf = dd.read_parquet('/Volumes/T7/melted-bids/bid-price-melted.parquet')

# # Force a simple RangeIndex
# volume_ddf = volume_ddf.reset_index(drop=True)
# price_ddf = price_ddf.reset_index(drop=True)

# # Convert SETTLEMENTDATE to datetime if needed
# volume_ddf["SETTLEMENTDATE"] = dd.to_datetime(volume_ddf["SETTLEMENTDATE"])
# price_ddf["SETTLEMENTDATE"] = dd.to_datetime(price_ddf["SETTLEMENTDATE"])

# # Force DUID etc. to be strings/ints consistently
# volume_ddf["DUID"] = volume_ddf["DUID"].astype(str)
# price_ddf["DUID"] = price_ddf["DUID"].astype(str)

# # Merge
# merged_ddf = volume_ddf.merge(
#     price_ddf,
#     on=["SETTLEMENTDATE","DUID","BIDTYPE","BIDBAND"],
#     how="inner"
# )

# merged_pdf = merged_ddf.compute()  # Should now work

AttributeError: 'Index' object has no attribute '_get_attributes_dict'

In [ ]:
# import os
# import dask.dataframe as dd
# import glob

# def load_all_parquet_dask(parquet_dir):
#     # Identify all Parquet files
#     all_files = glob.glob(os.path.join(parquet_dir, "*.parquet"))
#     # Filter out '._' hidden files
#     parquet_files = [f for f in all_files if not os.path.basename(f).startswith("._")]
#     # Read them into a Dask DataFrame
#     return dd.read_parquet(parquet_files)

# def main():
#     bid_volume_path = '/Volumes/T7/bid-volume-enriched'
#     bid_price_path = '/Volumes/T7/bid-price-filtered'
    
#     print("Loading volume data with Dask...")
#     volume_ddf = load_all_parquet_dask(bid_volume_path)
#     print(volume_ddf.head())  # just to show some data

#     print("Loading price data with Dask...")
#     price_ddf = load_all_parquet_dask(bid_price_path)
#     print(price_ddf.head())  # just to show some data

#     merged_ddf = volume_ddf.merge(
#     price_ddf,
#     on=["SETTLEMENTDATE", "DUID", "BIDTYPE"],
#     how="inner")

#     merged_pdf = merged_ddf.compute()
#     print(f"Merged DataFrame in memory: {merged_pdf.shape}")

#     # Otherwise, you can save the merged result to disk in Parquet or CSV:
#     # (But be aware that saving to CSV with Dask will create multiple partitions
#     # unless you do `coalesce` or `repartition(npartitions=1)`.)
#     output_dir = "/Volumes/T7/complete-bids"
#     merged_ddf.to_parquet(output_dir, overwrite=True)
#     print(f"Saved merged data to {output_dir}")

# if __name__ == "__main__":
#     main()