In [1]:
import awswrangler as wr

# Path to your S3 folder containing Parquet files
s3_path = "s3://thesis--ec331-s3/FCAS_RAISE1SEC-Volume-Bids/PUBLIC_DVD_BIDPEROFFER1_202311010000.parquet/"

# Read all Parquet files from the folder into a single DataFrame
df = wr.s3.read_parquet(path=s3_path)

# Now df contains all data from all Parquet files in the folder
# Display the first few rows to verify
df.head()

,I,BIDS,BIDOFFERPERIOD,1,DUID,BIDTYPE,TRADINGDATE,OFFERDATETIME,PERIODID,MAXAVAIL,...,BANDAVAIL2,BANDAVAIL3,BANDAVAIL4,BANDAVAIL5,BANDAVAIL6,BANDAVAIL7,BANDAVAIL8,BANDAVAIL9,BANDAVAIL10,PASAAVAILABILITY
0,D,BIDS,BIDOFFERPERIOD,1.0,ASQENC1,RAISE1SEC,2023/11/01 00:00:00,2023/10/31 11:39:18,5.0,11.0,...,0.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,11.0,NaN
1,D,BIDS,BIDOFFERPERIOD,1.0,ASQENC1,RAISE1SEC,2023/11/01 00:00:00,2023/10/31 11:39:18,1.0,11.0,...,0.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,11.0,NaN
2,D,BIDS,BIDOFFERPERIOD,1.0,ASQENC1,RAISE1SEC,2023/11/01 00:00:00,2023/10/31 11:39:18,2.0,11.0,...,0.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,11.0,NaN
3,D,BIDS,BIDOFFERPERIOD,1.0,ASQENC1,RAISE1SEC,2023/11/01 00:00:00,2023/10/31 11:39:18,3.0,11.0,...,0.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,11.0,NaN
4,D,BIDS,BIDOFFERPERIOD,1.0,ASQENC1,RAISE1SEC,2023/11/01 00:00:00,2023/10/31 11:39:18,4.0,11.0,...,0.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,11.0,NaN

In [2]:
df.columns

Index(['I', 'BIDS', 'BIDOFFERPERIOD', '1', 'DUID', 'BIDTYPE', 'TRADINGDATE',
       'OFFERDATETIME', 'PERIODID', 'MAXAVAIL', 'FIXEDLOAD', 'RAMPUPRATE',
       'RAMPDOWNRATE', 'ENABLEMENTMIN', 'ENABLEMENTMAX', 'LOWBREAKPOINT',
       'HIGHBREAKPOINT', 'BANDAVAIL1', 'BANDAVAIL2', 'BANDAVAIL3',
       'BANDAVAIL4', 'BANDAVAIL5', 'BANDAVAIL6', 'BANDAVAIL7', 'BANDAVAIL8',
       'BANDAVAIL9', 'BANDAVAIL10', 'PASAAVAILABILITY'],
      dtype='object')

In [7]:
# To find the first (earliest) datetime
first_datetime = df['TRADINGDATE'].min()

# To find the last (latest) datetime
last_datetime = df['TRADINGDATE'].max()

# Print the results
print(f"First datetime: {first_datetime}")
print(f"Last datetime: {last_datetime}")

First datetime: 2023/11/01 00:00:00
Last datetime: 2023/11/15 00:00:00

In [3]:
# Load price bids
s3_path = "s3://thesis--ec331-s3/FCAS_RAISE1SEC-Price-Bids/RAISE1SEC_FILTERED_202311010000.parquet"

# Read all Parquet files from the folder into a single DataFrame
price_df = wr.s3.read_parquet(path=s3_path)

# Now df contains all data from all Parquet files in the folder
# Display the first few rows to verify
price_df.head()

,I,BIDS,BIDDAYOFFER,1,DUID,BIDTYPE,SETTLEMENTDATE,OFFERDATE,VERSIONNO,PARTICIPANTID,...,T3,T4,NORMALSTATUS,LASTCHANGED,ENTRYTYPE,REBID_EVENT_TIME,REBID_AWARE_TIME,REBID_DECISION_TIME,REBID_CATEGORY,REFERENCE_ID
206568,D,BIDS,BIDDAYOFFER,1.0,ASNAES1,RAISE1SEC,2023/11/01 00:00:00,2023/10/31 11:03:31,1.0,AMALMASP,...,NaN,NaN,NaN,2023/10/31 11:03:31,DAILY,<NA>,<NA>,<NA>,<NA>,af680612-525b-4658-a81a-b371b8088309
206569,D,BIDS,BIDDAYOFFER,1.0,ASNAES1,RAISE1SEC,2023/11/02 00:00:00,2023/11/01 11:02:56,1.0,AMALMASP,...,NaN,NaN,NaN,2023/11/01 11:02:56,DAILY,<NA>,<NA>,<NA>,<NA>,7ae3c4a4-76c6-4d8b-9b51-8fa23cea93af
206570,D,BIDS,BIDDAYOFFER,1.0,ASNAES1,RAISE1SEC,2023/11/03 00:00:00,2023/11/02 11:02:55,1.0,AMALMASP,...,NaN,NaN,NaN,2023/11/02 11:02:55,DAILY,<NA>,<NA>,<NA>,<NA>,967bf01c-94c0-47b2-9d34-89e74a03baf5
206571,D,BIDS,BIDDAYOFFER,1.0,ASNAES1,RAISE1SEC,2023/11/04 00:00:00,2023/11/03 11:03:21,1.0,AMALMASP,...,NaN,NaN,NaN,2023/11/03 11:03:21,DAILY,<NA>,<NA>,<NA>,<NA>,893d3d8e-de19-4235-97c5-ac66c986de78
206572,D,BIDS,BIDDAYOFFER,1.0,ASNAES1,RAISE1SEC,2023/11/05 00:00:00,2023/11/04 11:03:30,1.0,AMALMASP,...,NaN,NaN,NaN,2023/11/04 11:03:30,DAILY,<NA>,<NA>,<NA>,<NA>,79129f9f-0ece-4820-b554-fbde07c6d688

In [4]:
price_df.columns

Index(['I', 'BIDS', 'BIDDAYOFFER', '1', 'DUID', 'BIDTYPE', 'SETTLEMENTDATE',
       'OFFERDATE', 'VERSIONNO', 'PARTICIPANTID', 'DAILYENERGYCONSTRAINT',
       'REBIDEXPLANATION', 'PRICEBAND1', 'PRICEBAND2', 'PRICEBAND3',
       'PRICEBAND4', 'PRICEBAND5', 'PRICEBAND6', 'PRICEBAND7', 'PRICEBAND8',
       'PRICEBAND9', 'PRICEBAND10', 'MINIMUMLOAD', 'T1', 'T2', 'T3', 'T4',
       'NORMALSTATUS', 'LASTCHANGED', 'ENTRYTYPE', 'REBID_EVENT_TIME',
       'REBID_AWARE_TIME', 'REBID_DECISION_TIME', 'REBID_CATEGORY',
       'REFERENCE_ID'],
      dtype='object')

In [5]:
price_df.shape

(149010, 35)

In [6]:
# To find the first (earliest) datetime
first_datetime = price_df['SETTLEMENTDATE'].min()

# To find the last (latest) datetime
last_datetime = price_df['SETTLEMENTDATE'].max()

# Print the results
print(f"First datetime: {first_datetime}")
print(f"Last datetime: {last_datetime}")

First datetime: 2023/11/01 00:00:00
Last datetime: 2023/11/30 00:00:00

In [18]:
import pandas as pd
import numpy as np
import awswrangler as wr
import time

# Add timing and logging
print("Starting data load...")
start_time = time.time()

# # Read all Parquet files from the S3 folder
# s3_path = "s3://thesis--ec331-s3/FCAS_RAISE1SEC-Volume-Bids/PUBLIC_DVD_BIDPEROFFER1_202311010000.parquet/"
# df = wr.s3.read_parquet(path=s3_path)

print(f"Data loaded in {time.time() - start_time:.2f} seconds")
print(f"DataFrame shape: {df.shape}")
print(f"Memory usage: {df.memory_usage().sum() / 1024 / 1024:.2f} MB")

# Print some sample data to understand structure
print("\nSample data:")
sample = filtered_df.sample(3)
print(sample[["DUID", "TRADINGDATE", "PERIODID", "MAXAVAIL"] + 
      [f"PRICEBAND{i}" for i in range(1, 11)] + 
      [f"BANDAVAIL{i}" for i in range(1, 11)]])

# Define a more vectorized approach for capping
def cap_bands_vectorized(df):
    print(f"Processing {len(df)} rows with vectorized approach...")
    start_time = time.time()
    
    # Create a copy to avoid modifying the original
    result_df = df.copy()
    
    # Process each row
    for idx, row in df.iterrows():
        max_avail = row["MAXAVAIL"]
        
        # Extract prices and volumes
        prices = [row.get(f"PRICEBAND{i}", np.nan) for i in range(1, 11)]
        volumes = [row.get(f"BANDAVAIL{i}", 0.0) for i in range(1, 11)]
        
        # Replace NaN volumes with 0
        volumes = [0.0 if pd.isna(v) else v for v in volumes]
        
        # Create a list of (price, volume, band_index)
        bands = [(p, v, i) for i, (p, v) in enumerate(zip(prices, volumes), 1) if not pd.isna(p)]
        
        # Sort by price
        bands.sort(key=lambda x: x[0])
        
        # Apply capping
        running_sum = 0.0
        capped_volumes = [0.0] * 10
        
        for price, volume, idx in bands:
            if running_sum >= max_avail:
                break
                
            remaining = max_avail - running_sum
            capped_volume = min(volume, remaining)
            
            capped_volumes[idx-1] = capped_volume
            running_sum += capped_volume
        
        # Update the result dataframe
        for i in range(1, 11):
            col = f"BANDAVAIL{i}"
            if col in result_df.columns:
                result_df.at[idx, col] = capped_volumes[i-1]
    
    print(f"Vectorized processing completed in {time.time() - start_time:.2f} seconds")
    return result_df

# Process in smaller chunks
print("\nProcessing data in chunks...")
chunk_size = 500
capped_dfs = []

for i in range(0, len(df), chunk_size):
    print(f"Processing chunk {i//chunk_size + 1}/{(len(df) + chunk_size - 1)//chunk_size}")
    chunk_start = time.time()
    
    # Get chunk
    chunk = df.iloc[i:i+chunk_size].copy()
    
    # Process chunk
    capped_chunk = chunk.groupby(["DUID", "TRADINGDATE", "PERIODID"]).apply(cap_bands_vectorized)
    capped_dfs.append(capped_chunk)
    
    print(f"Chunk completed in {time.time() - chunk_start:.2f} seconds")

# Combine results
if capped_dfs:
    capped_df = pd.concat(capped_dfs)
    print(f"\nAll processing completed in {time.time() - start_time:.2f} seconds")
    print(capped_df.head())
else:
    print("No results produced")

Starting data load...
Data loaded in 0.00 seconds
DataFrame shape: (21021120, 28)
Memory usage: 4490.60 MB

Sample data:

KeyError: "['PRICEBAND1', 'PRICEBAND2', 'PRICEBAND3', 'PRICEBAND4', 'PRICEBAND5', 'PRICEBAND6', 'PRICEBAND7', 'PRICEBAND8', 'PRICEBAND9', 'PRICEBAND10'] not in index"