In [1]:
import pandas as pd

# Define the file path
file_path = 's3://thesis--ec331-s3/enriched-volume-bids/RAISE1SEC_PUBLIC_DVD_BIDPEROFFER2_202310010000_enriched/enriched_volume_bids_20250312_102609_chunk1000of2123.parquet'

# Read the CSV file into a DataFrame, skipping the first row
df = pd.read_parquet(file_path)

# Display general information about the DataFrame
print("DataFrame Info:")
df.info()

# Show the first few rows of the DataFrame
df.head()

# Show the last few rows of the DataFrame
print("\nDataFrame Tail:")
print(df.tail())

# Display descriptive statistics for numerical columns
print("\nDataFrame Description:")
print(df.describe(include='all'))

# List all column names
print("\nDataFrame Columns:")
print(df.columns.tolist())

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 47 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   I                             10000 non-null  string
 1   BIDS                          10000 non-null  string
 2   BIDOFFERPERIOD                10000 non-null  string
 3   1                             10000 non-null  float64
 4   DUID                          10000 non-null  object
 5   BIDTYPE                       10000 non-null  string
 6   TRADINGDATE                   10000 non-null  string
 7   OFFERDATETIME                 10000 non-null  string
 8   PERIODID                      10000 non-null  float64
 9   MAXAVAIL                      10000 non-null  float64
 10  FIXEDLOAD                     0 non-null      float64
 11  RAMPUPRATE                    0 non-null      float64
 12  RAMPDOWNRATE                  0 non-null      float64
 13  ENABLEMENTMIN                 10000 non-null  float64
 14  ENABLEMENTMAX                 10000 non-null  float64
 15  LOWBREAKPOINT                 10000 non-null  float64
 16  HIGHBREAKPOINT                10000 non-null  float64
 17  BANDAVAIL1                    10000 non-null  float64
 18  BANDAVAIL2                    10000 non-null  float64
 19  BANDAVAIL3                    10000 non-null  float64
 20  BANDAVAIL4                    10000 non-null  float64
 21  BANDAVAIL5                    10000 non-null  float64
 22  BANDAVAIL6                    10000 non-null  float64
 23  BANDAVAIL7                    10000 non-null  float64
 24  BANDAVAIL8                    10000 non-null  float64
 25  BANDAVAIL9                    10000 non-null  float64
 26  BANDAVAIL10                   10000 non-null  float64
 27  PASAAVAILABILITY              0 non-null      float64
 28  Participant                   0 non-null      object
 29  Station_Name                  0 non-null      object
 30  Region                        0 non-null      object
 31  Dispatch_Type                 0 non-null      object
 32  Category                      0 non-null      object
 33  Classification                0 non-null      object
 34  Fuel_Source_-_Primary         0 non-null      object
 35  Fuel_Source_-_Descriptor      0 non-null      object
 36  Technology_Type_-_Primary     0 non-null      object
 37  Technology_Type_-_Descriptor  0 non-null      object
 38  Units                         0 non-null      object
 39  Aggregation                   0 non-null      object
 40  Reg_Cap_generation__MW_       0 non-null      object
 41  Max_Cap_generation__MW_       0 non-null      object
 42  Max_ROC/Min_generation        0 non-null      object
 43  Reg_Cap_consumption__MW_      0 non-null      float64
 44  Max_Cap_consumption__MW_      0 non-null      float64
 45  Max_ROC/Min_consumption       0 non-null      float64
 46  Comments                      0 non-null      float64
dtypes: float64(25), object(16), string(6)
memory usage: 3.6+ MB

DataFrame Tail:
      I  BIDS  BIDOFFERPERIOD    1      DUID    BIDTYPE          TRADINGDATE  \
9995  D  BIDS  BIDOFFERPERIOD  1.0  DRVIOT02  RAISE1SEC  2023/10/21 00:00:00
9996  D  BIDS  BIDOFFERPERIOD  1.0  DRVIOT02  RAISE1SEC  2023/10/21 00:00:00
9997  D  BIDS  BIDOFFERPERIOD  1.0  DRVIOT02  RAISE1SEC  2023/10/21 00:00:00
9998  D  BIDS  BIDOFFERPERIOD  1.0  DRVIOT02  RAISE1SEC  2023/10/21 00:00:00
9999  D  BIDS  BIDOFFERPERIOD  1.0  DRVIOT02  RAISE1SEC  2023/10/21 00:00:00

            OFFERDATETIME  PERIODID  MAXAVAIL  ...  \
9995  2023/10/21 09:07:45      85.0       0.0  ...
9996  2023/10/21 09:07:45      86.0       0.0  ...
9997  2023/10/21 09:07:45      87.0       0.0  ...
9998  2023/10/21 09:07:45      88.0       0.0  ...
9999  2023/10/21 09:07:45      89.0       1.0  ...

      Technology_Type_-_Descriptor  Units  Aggregation  \
9995                          None   None         None
9996                          None   None         None
9997                          None   None         None
9998                          None   None         None
9999                          None   None         None

      Reg_Cap_generation__MW_  Max_Cap_generation__MW_  \
9995                     None                     None
9996                     None                     None
9997                     None                     None
9998                     None                     None
9999                     None                     None

      Max_ROC/Min_generation  Reg_Cap_consumption__MW_  \
9995                    None                       NaN
9996                    None                       NaN
9997                    None                       NaN
9998                    None                       NaN
9999                    None                       NaN

      Max_Cap_consumption__MW_  Max_ROC/Min_consumption  Comments
9995                       NaN                      NaN       NaN
9996                       NaN                      NaN       NaN
9997                       NaN                      NaN       NaN
9998                       NaN                      NaN       NaN
9999                       NaN                      NaN       NaN

[5 rows x 47 columns]

DataFrame Description:
            I   BIDS  BIDOFFERPERIOD        1      DUID    BIDTYPE  \
count   10000  10000           10000  10000.0     10000      10000
unique      1      1               1      NaN         1          1
top         D   BIDS  BIDOFFERPERIOD      NaN  DRVIOT02  RAISE1SEC
freq    10000  10000           10000      NaN     10000      10000
mean      NaN    NaN             NaN      1.0       NaN        NaN
std       NaN    NaN             NaN      0.0       NaN        NaN
min       NaN    NaN             NaN      1.0       NaN        NaN
25%       NaN    NaN             NaN      1.0       NaN        NaN
50%       NaN    NaN             NaN      1.0       NaN        NaN
75%       NaN    NaN             NaN      1.0       NaN        NaN
max       NaN    NaN             NaN      1.0       NaN        NaN

                TRADINGDATE        OFFERDATETIME     PERIODID      MAXAVAIL  \
count                 10000                10000  10000.00000  10000.000000
unique                    2                   69          NaN           NaN
top     2023/10/21 00:00:00  2023/10/21 06:02:47          NaN           NaN
freq                   9702                  253          NaN           NaN
mean                    NaN                  NaN    133.94730      0.500700
std                     NaN                  NaN     79.43858      0.500025
min                     NaN                  NaN      1.00000      0.000000
25%                     NaN                  NaN     69.00000      0.000000
50%                     NaN                  NaN    125.00000      1.000000
75%                     NaN                  NaN    198.00000      1.000000
max                     NaN                  NaN    288.00000      1.000000

        ...  Technology_Type_-_Descriptor  Units  Aggregation  \
count   ...                             0      0            0
unique  ...                             0      0            0
top     ...                           NaN    NaN          NaN
freq    ...                           NaN    NaN          NaN
mean    ...                           NaN    NaN          NaN
std     ...                           NaN    NaN          NaN
min     ...                           NaN    NaN          NaN
25%     ...                           NaN    NaN          NaN
50%     ...                           NaN    NaN          NaN
75%     ...                           NaN    NaN          NaN
max     ...                           NaN    NaN          NaN

        Reg_Cap_generation__MW_  Max_Cap_generation__MW_  \
count                         0                        0
unique                        0                        0
top                         NaN                      NaN
freq                        NaN                      NaN
mean                        NaN                      NaN
std                         NaN                      NaN
min                         NaN                      NaN
25%                         NaN                      NaN
50%                         NaN                      NaN
75%                         NaN                      NaN
max                         NaN                      NaN

        Max_ROC/Min_generation  Reg_Cap_consumption__MW_  \
count                        0                       0.0
unique                       0                       NaN
top                        NaN                       NaN
freq                       NaN                       NaN
mean                       NaN                       NaN
std                        NaN                       NaN
min                        NaN                       NaN
25%                        NaN                       NaN
50%                        NaN                       NaN
75%                        NaN                       NaN
max                        NaN                       NaN

        Max_Cap_consumption__MW_  Max_ROC/Min_consumption  Comments
count                        0.0                      0.0       0.0
unique                       NaN                      NaN       NaN
top                          NaN                      NaN       NaN
freq                         NaN                      NaN       NaN
mean                         NaN                      NaN       NaN
std                          NaN                      NaN       NaN
min                          NaN                      NaN       NaN
25%                          NaN                      NaN       NaN
50%                          NaN                      NaN       NaN
75%                          NaN                      NaN       NaN
max                          NaN                      NaN       NaN

[11 rows x 47 columns]

DataFrame Columns:
['I', 'BIDS', 'BIDOFFERPERIOD', '1', 'DUID', 'BIDTYPE', 'TRADINGDATE', 'OFFERDATETIME', 'PERIODID', 'MAXAVAIL', 'FIXEDLOAD', 'RAMPUPRATE', 'RAMPDOWNRATE', 'ENABLEMENTMIN', 'ENABLEMENTMAX', 'LOWBREAKPOINT', 'HIGHBREAKPOINT', 'BANDAVAIL1', 'BANDAVAIL2', 'BANDAVAIL3', 'BANDAVAIL4', 'BANDAVAIL5', 'BANDAVAIL6', 'BANDAVAIL7', 'BANDAVAIL8', 'BANDAVAIL9', 'BANDAVAIL10', 'PASAAVAILABILITY', 'Participant', 'Station_Name', 'Region', 'Dispatch_Type', 'Category', 'Classification', 'Fuel_Source_-_Primary', 'Fuel_Source_-_Descriptor', 'Technology_Type_-_Primary', 'Technology_Type_-_Descriptor', 'Units', 'Aggregation', 'Reg_Cap_generation__MW_', 'Max_Cap_generation__MW_', 'Max_ROC/Min_generation', 'Reg_Cap_consumption__MW_', 'Max_Cap_consumption__MW_', 'Max_ROC/Min_consumption', 'Comments']

In [3]:
import pandas as pd

# Define the file path
file_path = 's3://thesis--ec331-s3/melted-price-bids/RAISE1SEC_FILTERED_202310010000/raise1sec_bids_melted_20250315175551_part0001.parquet'

# Read the CSV file into a DataFrame, skipping the first row
df = pd.read_parquet(file_path)

# Display general information about the DataFrame
print("DataFrame Info:")
df.info()

# Show the first few rows of the DataFrame
print("\nDataFrame Head:")
print(df.head())

# Show the last few rows of the DataFrame
print("\nDataFrame Tail:")
print(df.tail())

# Display descriptive statistics for numerical columns
print("\nDataFrame Description:")
print(df.describe(include='all'))

# List all column names
print("\nDataFrame Columns:")
print(df.columns.tolist())

# Display general information about the DataFrame
print("DataFrame Info:")
df.info()

# Show the first few rows of the DataFrame
print("\nDataFrame Head:")
print(df.head())

# Show the last few rows of the DataFrame
print("\nDataFrame Tail:")
print(df.tail())

# Display descriptive statistics for numerical columns
print("\nDataFrame Description:")
print(df.describe(include='all'))

# List all column names
print("\nDataFrame Columns:")
print(df.columns.tolist())

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 27 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   I                      500000 non-null  string
 1   BIDS                   500000 non-null  string
 2   BIDDAYOFFER            500000 non-null  string
 3   1                      500000 non-null  float64
 4   DUID                   500000 non-null  object
 5   BIDTYPE                500000 non-null  object
 6   SETTLEMENTDATE         500000 non-null  datetime64[ns]
 7   OFFERDATE              500000 non-null  string
 8   VERSIONNO              500000 non-null  float64
 9   PARTICIPANTID          500000 non-null  string
 10  DAILYENERGYCONSTRAINT  0 non-null       float64
 11  REBIDEXPLANATION       499450 non-null  string
 12  MINIMUMLOAD            100 non-null     float64
 13  T1                     0 non-null       float64
 14  T2                     0 non-null       float64
 15  T3                     0 non-null       float64
 16  T4                     0 non-null       float64
 17  NORMALSTATUS           0 non-null       float64
 18  LASTCHANGED            500000 non-null  string
 19  ENTRYTYPE              500000 non-null  string
 20  REBID_EVENT_TIME       499160 non-null  string
 21  REBID_AWARE_TIME       347760 non-null  string
 22  REBID_DECISION_TIME    347760 non-null  string
 23  REBID_CATEGORY         488660 non-null  string
 24  REFERENCE_ID           500000 non-null  string
 25  BIDBAND                500000 non-null  int64
 26  BIDPRICE               500000 non-null  float64
dtypes: datetime64[ns](1), float64(10), int64(1), object(2), string(13)
memory usage: 103.0+ MB

DataFrame Head:
   I  BIDS  BIDDAYOFFER    1     DUID    BIDTYPE SETTLEMENTDATE  \
0  D  BIDS  BIDDAYOFFER  1.0  ASNAES1  RAISE1SEC     2023-10-29
1  D  BIDS  BIDDAYOFFER  1.0  ASNAES1  RAISE1SEC     2023-10-31
2  D  BIDS  BIDDAYOFFER  1.0  ASNENC1  RAISE1SEC     2023-10-08
3  D  BIDS  BIDDAYOFFER  1.0  ASNENC1  RAISE1SEC     2023-10-09
4  D  BIDS  BIDDAYOFFER  1.0  ASNENC1  RAISE1SEC     2023-10-09

             OFFERDATE  VERSIONNO PARTICIPANTID  ...  NORMALSTATUS  \
0  2023/10/27 14:31:21        1.0      AMALMASP  ...           NaN
1  2023/10/30 11:02:53        1.0      AMALMASP  ...           NaN
2  2023/10/05 15:35:07        1.0      ENOCMASP  ...           NaN
3  2023/10/06 14:19:35        1.0      ENOCMASP  ...           NaN
4  2023/10/09 13:10:27        1.0      ENOCMASP  ...           NaN

           LASTCHANGED  ENTRYTYPE  REBID_EVENT_TIME  REBID_AWARE_TIME  \
0  2023/10/27 14:31:21      DAILY              <NA>              <NA>
1  2023/10/30 11:02:53      DAILY              <NA>              <NA>
2  2023/10/05 15:35:07      DAILY              <NA>              <NA>
3  2023/10/06 14:19:35      DAILY          15:15:00              <NA>
4  2023/10/09 13:10:27      REBID          13:08:00              <NA>

   REBID_DECISION_TIME  REBID_CATEGORY                          REFERENCE_ID  \
0                 <NA>            <NA>      BE737C9E9E234F998B18FE4B2F9AC2E8
1                 <NA>            <NA>  a529df1f-c7ac-45c5-8995-4fae5b45ce46
2                 <NA>            <NA>      2370F99E2EF34763BC4001A791AD49B9
3                 <NA>            <NA>  8f8661ba-0579-4ccb-9c99-80ba0f1f9a5d
4                 <NA>            <NA>  fb4c0f11-359e-47bf-a0ab-634a117b4390

  BIDBAND BIDPRICE
0       1      0.0
1       1      0.0
2       1      0.0
3       1      0.0
4       1      0.0

[5 rows x 27 columns]

DataFrame Tail:
        I  BIDS  BIDDAYOFFER    1      DUID    BIDTYPE SETTLEMENTDATE  \
499995  D  BIDS  BIDDAYOFFER  1.0  DRVIOT03  RAISE1SEC     2023-10-19
499996  D  BIDS  BIDDAYOFFER  1.0  DRVIOT03  RAISE1SEC     2023-10-19
499997  D  BIDS  BIDDAYOFFER  1.0  DRVIOT03  RAISE1SEC     2023-10-19
499998  D  BIDS  BIDDAYOFFER  1.0  DRVIOT03  RAISE1SEC     2023-10-19
499999  D  BIDS  BIDDAYOFFER  1.0  DRVIOT03  RAISE1SEC     2023-10-19

                  OFFERDATE  VERSIONNO PARTICIPANTID  ...  NORMALSTATUS  \
499995  2023/10/19 10:37:52        1.0        VIOTAS  ...           NaN
499996  2023/10/19 10:42:45        1.0        VIOTAS  ...           NaN
499997  2023/10/19 10:47:48        1.0        VIOTAS  ...           NaN
499998  2023/10/19 10:52:47        1.0        VIOTAS  ...           NaN
499999  2023/10/19 10:57:46        1.0        VIOTAS  ...           NaN

                LASTCHANGED  ENTRYTYPE  REBID_EVENT_TIME  REBID_AWARE_TIME  \
499995  2023/10/19 10:37:52      REBID          10:37:24          10:37:24
499996  2023/10/19 10:42:45      REBID          10:42:21          10:42:21
499997  2023/10/19 10:47:48      REBID          10:47:24          10:47:24
499998  2023/10/19 10:52:47      REBID          10:52:23          10:52:23
499999  2023/10/19 10:57:46      REBID          10:57:22          10:57:22

        REBID_DECISION_TIME  REBID_CATEGORY  \
499995             10:37:24               P
499996             10:42:21               P
499997             10:47:24               P
499998             10:52:23               P
499999             10:57:22               P

                                REFERENCE_ID BIDBAND BIDPRICE
499995  60531f71-6180-43b9-af90-5d26b4b436c8      10  14990.0
499996  4e935e5d-8f56-421f-8925-6a3e9c948536      10  14990.0
499997  02e8f4a6-e468-4402-9ca3-9e51d17fc1d9      10  14990.0
499998  4ac19038-11ed-4f31-b287-4097d61012e1      10  14990.0
499999  753549ab-60d7-4780-95f4-fb33aa18b8db      10  14990.0

[5 rows x 27 columns]

DataFrame Description:
             I    BIDS  BIDDAYOFFER         1      DUID    BIDTYPE  \
count   500000  500000       500000  500000.0    500000     500000
unique       1       1            1       NaN        12          1
top          D    BIDS  BIDDAYOFFER       NaN  ASRMGE02  RAISE1SEC
freq    500000  500000       500000       NaN    108200     500000
mean       NaN     NaN          NaN       1.0       NaN        NaN
min        NaN     NaN          NaN       1.0       NaN        NaN
25%        NaN     NaN          NaN       1.0       NaN        NaN
50%        NaN     NaN          NaN       1.0       NaN        NaN
75%        NaN     NaN          NaN       1.0       NaN        NaN
max        NaN     NaN          NaN       1.0       NaN        NaN
std        NaN     NaN          NaN       0.0       NaN        NaN

                       SETTLEMENTDATE            OFFERDATE  VERSIONNO  \
count                          500000               500000   500000.0
unique                            NaN                39987        NaN
top                               NaN  2023/10/09 22:43:18        NaN
freq                              NaN                   40        NaN
mean    2023-10-19 22:28:40.512000512                  NaN        1.0
min               2023-10-08 00:00:00                  NaN        1.0
25%               2023-10-14 00:00:00                  NaN        1.0
50%               2023-10-20 00:00:00                  NaN        1.0
75%               2023-10-26 00:00:00                  NaN        1.0
max               2023-10-31 00:00:00                  NaN        1.0
std                               NaN                  NaN        0.0

       PARTICIPANTID  ...  NORMALSTATUS          LASTCHANGED  ENTRYTYPE  \
count         500000  ...           0.0               500000     500000
unique             6  ...           NaN                39987          2
top            YESSA  ...           NaN  2023/10/09 22:43:18      REBID
freq          323960  ...           NaN                   40     494360
mean             NaN  ...           NaN                  NaN        NaN
min              NaN  ...           NaN                  NaN        NaN
25%              NaN  ...           NaN                  NaN        NaN
50%              NaN  ...           NaN                  NaN        NaN
75%              NaN  ...           NaN                  NaN        NaN
max              NaN  ...           NaN                  NaN        NaN
std              NaN  ...           NaN                  NaN        NaN

        REBID_EVENT_TIME  REBID_AWARE_TIME  REBID_DECISION_TIME  \
count             499160            347760               347760
unique              4014              2591                 2639
top             18:35:34          18:35:42             02:08:00
freq               67420             67420                  990
mean                 NaN               NaN                  NaN
min                  NaN               NaN                  NaN
25%                  NaN               NaN                  NaN
50%                  NaN               NaN                  NaN
75%                  NaN               NaN                  NaN
max                  NaN               NaN                  NaN
std                  NaN               NaN                  NaN

        REBID_CATEGORY                          REFERENCE_ID        BIDBAND  \
count           488660                                500000  500000.000000
unique               4                                 40075            NaN
top                  A  d6d79858-61ac-4ea2-968e-8d3305f3d825            NaN
freq            183000                                    30            NaN
mean               NaN                                   NaN       5.500000
min                NaN                                   NaN       1.000000
25%                NaN                                   NaN       3.000000
50%                NaN                                   NaN       5.500000
75%                NaN                                   NaN       8.000000
max                NaN                                   NaN      10.000000
std                NaN                                   NaN       2.872284

             BIDPRICE
count   500000.000000
unique            NaN
top               NaN
freq              NaN
mean      1630.780625
min          0.000000
25%          0.950000
50%          4.300000
75%         40.250000
max      16600.000000
std       4811.795927

[11 rows x 27 columns]

DataFrame Columns:
['I', 'BIDS', 'BIDDAYOFFER', '1', 'DUID', 'BIDTYPE', 'SETTLEMENTDATE', 'OFFERDATE', 'VERSIONNO', 'PARTICIPANTID', 'DAILYENERGYCONSTRAINT', 'REBIDEXPLANATION', 'MINIMUMLOAD', 'T1', 'T2', 'T3', 'T4', 'NORMALSTATUS', 'LASTCHANGED', 'ENTRYTYPE', 'REBID_EVENT_TIME', 'REBID_AWARE_TIME', 'REBID_DECISION_TIME', 'REBID_CATEGORY', 'REFERENCE_ID', 'BIDBAND', 'BIDPRICE']
DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 27 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   I                      500000 non-null  string
 1   BIDS                   500000 non-null  string
 2   BIDDAYOFFER            500000 non-null  string
 3   1                      500000 non-null  float64
 4   DUID                   500000 non-null  object
 5   BIDTYPE                500000 non-null  object
 6   SETTLEMENTDATE         500000 non-null  datetime64[ns]
 7   OFFERDATE              500000 non-null  string
 8   VERSIONNO              500000 non-null  float64
 9   PARTICIPANTID          500000 non-null  string
 10  DAILYENERGYCONSTRAINT  0 non-null       float64
 11  REBIDEXPLANATION       499450 non-null  string
 12  MINIMUMLOAD            100 non-null     float64
 13  T1                     0 non-null       float64
 14  T2                     0 non-null       float64
 15  T3                     0 non-null       float64
 16  T4                     0 non-null       float64
 17  NORMALSTATUS           0 non-null       float64
 18  LASTCHANGED            500000 non-null  string
 19  ENTRYTYPE              500000 non-null  string
 20  REBID_EVENT_TIME       499160 non-null  string
 21  REBID_AWARE_TIME       347760 non-null  string
 22  REBID_DECISION_TIME    347760 non-null  string
 23  REBID_CATEGORY         488660 non-null  string
 24  REFERENCE_ID           500000 non-null  string
 25  BIDBAND                500000 non-null  int64
 26  BIDPRICE               500000 non-null  float64
dtypes: datetime64[ns](1), float64(10), int64(1), object(2), string(13)
memory usage: 103.0+ MB

DataFrame Head:
   I  BIDS  BIDDAYOFFER    1     DUID    BIDTYPE SETTLEMENTDATE  \
0  D  BIDS  BIDDAYOFFER  1.0  ASNAES1  RAISE1SEC     2023-10-29
1  D  BIDS  BIDDAYOFFER  1.0  ASNAES1  RAISE1SEC     2023-10-31
2  D  BIDS  BIDDAYOFFER  1.0  ASNENC1  RAISE1SEC     2023-10-08
3  D  BIDS  BIDDAYOFFER  1.0  ASNENC1  RAISE1SEC     2023-10-09
4  D  BIDS  BIDDAYOFFER  1.0  ASNENC1  RAISE1SEC     2023-10-09

             OFFERDATE  VERSIONNO PARTICIPANTID  ...  NORMALSTATUS  \
0  2023/10/27 14:31:21        1.0      AMALMASP  ...           NaN
1  2023/10/30 11:02:53        1.0      AMALMASP  ...           NaN
2  2023/10/05 15:35:07        1.0      ENOCMASP  ...           NaN
3  2023/10/06 14:19:35        1.0      ENOCMASP  ...           NaN
4  2023/10/09 13:10:27        1.0      ENOCMASP  ...           NaN

           LASTCHANGED  ENTRYTYPE  REBID_EVENT_TIME  REBID_AWARE_TIME  \
0  2023/10/27 14:31:21      DAILY              <NA>              <NA>
1  2023/10/30 11:02:53      DAILY              <NA>              <NA>
2  2023/10/05 15:35:07      DAILY              <NA>              <NA>
3  2023/10/06 14:19:35      DAILY          15:15:00              <NA>
4  2023/10/09 13:10:27      REBID          13:08:00              <NA>

   REBID_DECISION_TIME  REBID_CATEGORY                          REFERENCE_ID  \
0                 <NA>            <NA>      BE737C9E9E234F998B18FE4B2F9AC2E8
1                 <NA>            <NA>  a529df1f-c7ac-45c5-8995-4fae5b45ce46
2                 <NA>            <NA>      2370F99E2EF34763BC4001A791AD49B9
3                 <NA>            <NA>  8f8661ba-0579-4ccb-9c99-80ba0f1f9a5d
4                 <NA>            <NA>  fb4c0f11-359e-47bf-a0ab-634a117b4390

  BIDBAND BIDPRICE
0       1      0.0
1       1      0.0
2       1      0.0
3       1      0.0
4       1      0.0

[5 rows x 27 columns]

DataFrame Tail:
        I  BIDS  BIDDAYOFFER    1      DUID    BIDTYPE SETTLEMENTDATE  \
499995  D  BIDS  BIDDAYOFFER  1.0  DRVIOT03  RAISE1SEC     2023-10-19
499996  D  BIDS  BIDDAYOFFER  1.0  DRVIOT03  RAISE1SEC     2023-10-19
499997  D  BIDS  BIDDAYOFFER  1.0  DRVIOT03  RAISE1SEC     2023-10-19
499998  D  BIDS  BIDDAYOFFER  1.0  DRVIOT03  RAISE1SEC     2023-10-19
499999  D  BIDS  BIDDAYOFFER  1.0  DRVIOT03  RAISE1SEC     2023-10-19

                  OFFERDATE  VERSIONNO PARTICIPANTID  ...  NORMALSTATUS  \
499995  2023/10/19 10:37:52        1.0        VIOTAS  ...           NaN
499996  2023/10/19 10:42:45        1.0        VIOTAS  ...           NaN
499997  2023/10/19 10:47:48        1.0        VIOTAS  ...           NaN
499998  2023/10/19 10:52:47        1.0        VIOTAS  ...           NaN
499999  2023/10/19 10:57:46        1.0        VIOTAS  ...           NaN

                LASTCHANGED  ENTRYTYPE  REBID_EVENT_TIME  REBID_AWARE_TIME  \
499995  2023/10/19 10:37:52      REBID          10:37:24          10:37:24
499996  2023/10/19 10:42:45      REBID          10:42:21          10:42:21
499997  2023/10/19 10:47:48      REBID          10:47:24          10:47:24
499998  2023/10/19 10:52:47      REBID          10:52:23          10:52:23
499999  2023/10/19 10:57:46      REBID          10:57:22          10:57:22

        REBID_DECISION_TIME  REBID_CATEGORY  \
499995             10:37:24               P
499996             10:42:21               P
499997             10:47:24               P
499998             10:52:23               P
499999             10:57:22               P

                                REFERENCE_ID BIDBAND BIDPRICE
499995  60531f71-6180-43b9-af90-5d26b4b436c8      10  14990.0
499996  4e935e5d-8f56-421f-8925-6a3e9c948536      10  14990.0
499997  02e8f4a6-e468-4402-9ca3-9e51d17fc1d9      10  14990.0
499998  4ac19038-11ed-4f31-b287-4097d61012e1      10  14990.0
499999  753549ab-60d7-4780-95f4-fb33aa18b8db      10  14990.0

[5 rows x 27 columns]

DataFrame Description:
             I    BIDS  BIDDAYOFFER         1      DUID    BIDTYPE  \
count   500000  500000       500000  500000.0    500000     500000
unique       1       1            1       NaN        12          1
top          D    BIDS  BIDDAYOFFER       NaN  ASRMGE02  RAISE1SEC
freq    500000  500000       500000       NaN    108200     500000
mean       NaN     NaN          NaN       1.0       NaN        NaN
min        NaN     NaN          NaN       1.0       NaN        NaN
25%        NaN     NaN          NaN       1.0       NaN        NaN
50%        NaN     NaN          NaN       1.0       NaN        NaN
75%        NaN     NaN          NaN       1.0       NaN        NaN
max        NaN     NaN          NaN       1.0       NaN        NaN
std        NaN     NaN          NaN       0.0       NaN        NaN

                       SETTLEMENTDATE            OFFERDATE  VERSIONNO  \
count                          500000               500000   500000.0
unique                            NaN                39987        NaN
top                               NaN  2023/10/09 22:43:18        NaN
freq                              NaN                   40        NaN
mean    2023-10-19 22:28:40.512000512                  NaN        1.0
min               2023-10-08 00:00:00                  NaN        1.0
25%               2023-10-14 00:00:00                  NaN        1.0
50%               2023-10-20 00:00:00                  NaN        1.0
75%               2023-10-26 00:00:00                  NaN        1.0
max               2023-10-31 00:00:00                  NaN        1.0
std                               NaN                  NaN        0.0

       PARTICIPANTID  ...  NORMALSTATUS          LASTCHANGED  ENTRYTYPE  \
count         500000  ...           0.0               500000     500000
unique             6  ...           NaN                39987          2
top            YESSA  ...           NaN  2023/10/09 22:43:18      REBID
freq          323960  ...           NaN                   40     494360
mean             NaN  ...           NaN                  NaN        NaN
min              NaN  ...           NaN                  NaN        NaN
25%              NaN  ...           NaN                  NaN        NaN
50%              NaN  ...           NaN                  NaN        NaN
75%              NaN  ...           NaN                  NaN        NaN
max              NaN  ...           NaN                  NaN        NaN
std              NaN  ...           NaN                  NaN        NaN

        REBID_EVENT_TIME  REBID_AWARE_TIME  REBID_DECISION_TIME  \
count             499160            347760               347760
unique              4014              2591                 2639
top             18:35:34          18:35:42             02:08:00
freq               67420             67420                  990
mean                 NaN               NaN                  NaN
min                  NaN               NaN                  NaN
25%                  NaN               NaN                  NaN
50%                  NaN               NaN                  NaN
75%                  NaN               NaN                  NaN
max                  NaN               NaN                  NaN
std                  NaN               NaN                  NaN

        REBID_CATEGORY                          REFERENCE_ID        BIDBAND  \
count           488660                                500000  500000.000000
unique               4                                 40075            NaN
top                  A  d6d79858-61ac-4ea2-968e-8d3305f3d825            NaN
freq            183000                                    30            NaN
mean               NaN                                   NaN       5.500000
min                NaN                                   NaN       1.000000
25%                NaN                                   NaN       3.000000

In [7]:
import pandas as pd
import awswrangler as wr

# Set options to display all columns and increase column width
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 3000)           # Increase overall display width
pd.set_option('display.max_colwidth', 500)       # Increase the width of each column

# Path to the manifest file
manifest_path = "s3://thesis--ec331-s3/melted-price-bids/all_files_manifest_20250315134512.csv"

# Read the manifest
try:
    manifest_df = wr.s3.read_csv(manifest_path)
    print(f"Successfully read manifest file with {len(manifest_df)} entries")
    
    # Display the manifest with all columns and wider columns visible
    display(manifest_df)
    
except Exception as e:
    print(f"Error reading manifest file: {e}")

Successfully read manifest file with 9 entries

                                                                                                file_path                                                       file_name  batch_number  part_number
0  s3://thesis--ec331-s3/melted-price-bids/raise1sec_bids_melted_20250315134512_batch001_part0001.parquet  raise1sec_bids_melted_20250315134512_batch001_part0001.parquet             1            1
1  s3://thesis--ec331-s3/melted-price-bids/raise1sec_bids_melted_20250315134512_batch001_part0002.parquet  raise1sec_bids_melted_20250315134512_batch001_part0002.parquet             1            2
2  s3://thesis--ec331-s3/melted-price-bids/raise1sec_bids_melted_20250315134512_batch001_part0003.parquet  raise1sec_bids_melted_20250315134512_batch001_part0003.parquet             1            3
3  s3://thesis--ec331-s3/melted-price-bids/raise1sec_bids_melted_20250315134512_batch001_part0004.parquet  raise1sec_bids_melted_20250315134512_batch001_part0004.parquet             1            4
4  s3://thesis--ec331-s3/melted-price-bids/raise1sec_bids_melted_20250315134512_batch001_part0005.parquet  raise1sec_bids_melted_20250315134512_batch001_part0005.parquet             1            5
5  s3://thesis--ec331-s3/melted-price-bids/raise1sec_bids_melted_20250315134512_batch001_part0006.parquet  raise1sec_bids_melted_20250315134512_batch001_part0006.parquet             1            6
6  s3://thesis--ec331-s3/melted-price-bids/raise1sec_bids_melted_20250315134512_batch001_part0007.parquet  raise1sec_bids_melted_20250315134512_batch001_part0007.parquet             1            7
7  s3://thesis--ec331-s3/melted-price-bids/raise1sec_bids_melted_20250315134512_batch001_part0008.parquet  raise1sec_bids_melted_20250315134512_batch001_part0008.parquet             1            8
8  s3://thesis--ec331-s3/melted-price-bids/raise1sec_bids_melted_20250315134512_batch001_part0009.parquet  raise1sec_bids_melted_20250315134512_batch001_part0009.parquet             1            9

In [8]:
manifest_df['file_path'].unique

<bound method Series.unique of 0    s3://thesis--ec331-s3/melted-price-bids/raise1sec_bids_melted_20250315134512_batch001_part0001.parquet
1    s3://thesis--ec331-s3/melted-price-bids/raise1sec_bids_melted_20250315134512_batch001_part0002.parquet
2    s3://thesis--ec331-s3/melted-price-bids/raise1sec_bids_melted_20250315134512_batch001_part0003.parquet
3    s3://thesis--ec331-s3/melted-price-bids/raise1sec_bids_melted_20250315134512_batch001_part0004.parquet
4    s3://thesis--ec331-s3/melted-price-bids/raise1sec_bids_melted_20250315134512_batch001_part0005.parquet
5    s3://thesis--ec331-s3/melted-price-bids/raise1sec_bids_melted_20250315134512_batch001_part0006.parquet
6    s3://thesis--ec331-s3/melted-price-bids/raise1sec_bids_melted_20250315134512_batch001_part0007.parquet
7    s3://thesis--ec331-s3/melted-price-bids/raise1sec_bids_melted_20250315134512_batch001_part0008.parquet
8    s3://thesis--ec331-s3/melted-price-bids/raise1sec_bids_melted_20250315134512_batch001_part0009.parquet
Name: file_path, dtype: object>

In [9]:
import pandas as pd
import awswrangler as wr

# Set options to display all columns and increase column width
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 3000)           # Increase overall display width
pd.set_option('display.max_colwidth', 500)       # Increase the width of each column

# Path to the manifest file
manifest_path = "s3://thesis--ec331-s3/melted-price-bids/master_manifest_20250315134512.csv"

# Read the manifest
try:
    manifest_df = wr.s3.read_csv(manifest_path)
    print(f"Successfully read manifest file with {len(manifest_df)} entries")
    
    # Display the manifest with all columns and wider columns visible
    display(manifest_df)
    
except Exception as e:
    print(f"Error reading manifest file: {e}")

Successfully read manifest file with 1 entries

                                                                                        manifest_path
0  s3://thesis--ec331-s3/melted-price-bids/raise1sec_bids_melted_20250315134512_batch001_manifest.csv

In [ ]:
columns_df = pd.DataFrame(columns_list, columns=["Column_Name"])
columns_df.to_csv("all_columns.csv", index=False)

print("All columns have been saved to all_columns.csv")